image: juristr/angular-ci-build:1.0.0
stages:
  - build
  - deploy
  
before_script:
  - npm install
  - npm --prefix ./functions install
  
app-build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - npm run build:portfolio

deploy-production:
  stage: deploy
  dependencies:
    - app-build
  script:
    - npm run deploy
  only:
    - master